const choices = [
  {
    value: "id",
    label: "Id",
    label_ru: "Идентификатор",
    isFixed: true,
    visible_value: "Id",
    visible_label: "",
    visible: true,
  },
  {
    value: "name",
    label: "Name",
    label_ru: "Имя",
    isFixed: true,
    visible_value: "",
    visible_label: "",
    visible: true,
  },
  {
    value: "tags",
    label: "Tags",
    label_ru: "Тэги",
    isFixed: true,
    visible_value: "",
    visible_label: "",
    visible: true,
  },
  {
    value: "number1",
    label: "Number",
    label_ru: "Число",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "number2",
    label: "Number",
    label_ru: "Число",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "number3",
    label: "Number",
    label_ru: "Число",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "char1",
    label: "Single-line text",
    label_ru: "Однострочное поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "char2",
    label: "Single-line text",
    label_ru: "Однострочное поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "char3",
    label: "Single-line text",
    label_ru: "Однострочное поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "text1",
    label: "Markdown text line",
    label_ru: "Текстовое поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "text2",
    label: "Markdown text line",
    label_ru: "Текстовое поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "text3",
    label: "Markdown text line",
    label_ru: "Текстовое поле",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "checkbox1",
    label: "Checkbox",
    label_ru: "Чек-бокс",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "checkbox2",
    label: "Checkbox",
    label_ru: "Чек-бокс",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "checkbox3",
    label: "Checkbox",
    label_ru: "Чек-бокс",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "date1",
    label: "Date",
    label_ru: "Дата",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "date2",
    label: "Date",
    label_ru: "Дата",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
  {
    value: "date3",
    label: "Date",
    label_ru: "Дата",
    isFixed: false,
    visible_value: "",
    visible_label: "",
    visible: false,
  },
];
export default choices;

//visible_value is the name that you user wants to call the field!
