const dummyData = [
  {
    id: 1,
    name: "Adventure books",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ultrices metus at ex varius lacinia. Aliquam egestas vehicula lorem, sed tincidunt arcu accumsan vel. Sed hendrerit fermentum odio, eget consequat sapien ullamcorper eget. Vestibulum cursus, risus nec sagittis iaculis, turpis ante dignissim odio, ac dictum nulla sapien vitae nisl. Etiam a suscipit lectus. Phasellus diam sem, mollis vel blandit sit amet, rhoncus ut diam. Maecenas quis tempor tortor.",
    theme: "Books",
    image: "/bookshelf.svg",
    items: [
      {
        id: "1",
        name: "Cruzo's adventures1",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 1,
            name: "Pluto",
            value: "I'd love to read this book!",
          },
          {
            id: 2,
            name: "Alice",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 3,
            name: "John",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 667,
      },
      {
        id: "2",
        name: "Cruzo's adventures2",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 4,
            name: "Pluto1",
            value: "I'd love to read this book!",
          },
          {
            id: 5,
            name: "Alice1",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 6,
            name: "John1",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 66,
      },
    ],
  },
  {
    id: 2,
    name: "Romance books",
    description:
      "Sed condimentum, dolor vel fermentum pretium, elit nunc dictum arcu, vitae facilisis justo libero nec leo. Pellentesque mollis purus et erat egestas, et tempor mauris rhoncus. Aenean diam metus, elementum a iaculis sit amet, lacinia vitae purus. Aliquam erat volutpat. Sed eget luctus justo, sed hendrerit justo. Donec vel sagittis turpis. Donec nec scelerisque ex, non fermentum elit. Aenean eu odio id nulla dapibus sodales quis ut nulla. Mauris ac pharetra ex. Suspendisse porttitor, tellus vel ultrices aliquam, ligula quam iaculis magna.",
    theme: "Books",
    image: "/bookshelf.svg",
    items: [
      {
        id: "3",
        name: "Cruzo's adventures3",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 7,
            name: "Pluto3",
            value: "I'd love to read this book!",
          },
          {
            id: 8,
            name: "Alice3",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 9,
            name: "John3",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 667,
      },
      {
        id: "4",
        name: "Cruzo's adventures4",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 10,
            name: "Pluto2",
            value: "I'd love to read this book!",
          },
          {
            id: 11,
            name: "Alice2",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 12,
            name: "John2",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 66,
      },
    ],
  },
  {
    id: 3,
    name: "Fantasy books",
    description:
      "Mauris finibus lorem nec sem luctus, in accumsan risus aliquet. Fusce hendrerit mi non orci ullamcorper consequat. Aenean et tellus mollis, pharetra enim et, iaculis ligula. Nam pulvinar urna a ex feugiat egestas. Nulla a nisi vitae erat posuere pretium ut non ex. Cras ac fermentum justo. Cras et placerat nunc.",
    theme: "Books",
    image: "/bookshelf.svg",
    items: [
      {
        id: "3",
        name: "Cruzo's adventures3",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 7,
            name: "Pluto3",
            value: "I'd love to read this book!",
          },
          {
            id: 8,
            name: "Alice3",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 9,
            name: "John3",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 667,
      },
      {
        id: "4",
        name: "Cruzo's adventures4",
        tags: "adventures, XX, top adventures books",
        fields: {
          integer1: 1,
          integer2: "",
          integer3: "",
          char1: "",
          char2: "Mykola Liubachenko",
          char3: "",
          text1: "",
          text2: "Some text ~~about~~ *my life*",
          text3: "",
          date1: "01-20-20",
          date2: "",
          date3: "",
          checkbox1: "true",
          checkbox2: "",
          checkbox3: "",
          integer1_visible: 1,
          integer2_visible: "",
          integer3_visible: "",
          char1_visible: "",
          char2_visible: "visible",
          char3_visible: "",
          text1_visible: "",
          text2_visible: "visible",
          text3_visible: "",
          date1_visible: "visible",
          date2_visible: "",
          date3_visible: "",
          checkbox1_visible: "visible",
          checkbox2_visible: "",
          checkbox3_visible: "",
        },
        comments: [
          {
            id: 10,
            name: "Pluto2",
            value: "I'd love to read this book!",
          },
          {
            id: 11,
            name: "Alice2",
            value: "MMMMM !!! LOVE THIS!!",
          },
          {
            id: 12,
            name: "John2",
            value:
              "Alice and Pluto are bots! The book doesn't deserve the likes! What happens with this world!",
          },
        ],
        likes: 66,
      },
    ],
  },
];

export default dummyData;
